name: tests
on: [ push ]
jobs:
  npm-audit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Set up node latest
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm audit
        continue-on-error: true
  test:
    runs-on: ubuntu-22.04
    needs: npm-audit
    environment: prod
#    if: ${{ vars.DEPLOY == 'TRUE' }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up node latest
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm test
      - run: echo ${{ vars.DEPLOY }}